# Generated by Django 5.1 on 2024-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(default='', max_length=50)),
                ('Patient_Email', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=350)),
            ],
        ),
    ]
